import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './page.module.scss'
import { Header } from '@/components/header'
import Image from 'next/image'
import EarthImage from '@/assets/earth-background.svg'
import { EventProvider } from '@/context/EventContext'
// import { Drawer } from '@/components/drawer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <main className={styles.main}>
          <EventProvider>
            <Image
              width={1500}
              height={900}
              alt="image of planet earth"
              src={EarthImage}
              className={styles.backgroundImage}
            />
            <Header />
            {children}
          </EventProvider>
        </main>
      </body>
    </html>
  )
}
